---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Стоимость и описание товара должны отображаться в разных валютах в зависимости от выбранного языка
  - Пользователь должен иметь возможность сделать заказ без регистрации
  - Корзина хранится в сессии браузера
  - Данный интернет магазин работает, как SPA приложение
  - После добавления товара в корзину должно появляться сообщение об этом
  - При посещении сайта должна появляться надпись принятия cookie